### ISSUE TITLE
slow speed in dds setting of dict

### ISSUE THREAD

**Issue by lchunleo** [rticommunity/rticonnextdds-connector-py#137]
Hi
  i am checking out the image example, where i put in a image of 1920x 1080 or 640 x 480, i noted that the setting of dictionary takes about a few seconds. The given example works fast. Can advise? thank you

E.g. output.instance.set_dictionary({"pixels":flatten_frame})

**Comment by samuelraeburn** [comment]
What is the type definition your are using for the `pixels` member?
Potentially this could help you if it is a sequence: https://community.rti.com/kb/improve-performance-accessing-types-containing-sequences-and-arrays-rti-connector

**Comment by lchunleo** [comment]
Thanks..am using the example for images , the type is  in byte
