### ISSUE TITLE
connextdds blocking

### ISSUE THREAD

**Issue by Francisobiagwu** [rticommunity/rticonnextdds-connector-py#36]
### Information

- **RTI Product: python examples**:
- **Version: n/a**:
- **Operating system: ubuntu 19**:
- **Compiler: n/a**:
- **Compiler version: n/a **:
- **Additional information**:

### What is the current behavior?
Each time I modify the reader.py and writer.py example script. Let say, there is an error, maybe in the xml file or in the code, it seems like a kind of blocking mechanism is activated. When I run the reader.py the reader won't be able to read the data. Even when I fix the error by reverting the code to the original form, the reader won't work until I restart my computer. Please is there any explanation for this?

### Steps to reproduce the issue
modify the xml file to give an error, and then run the reader.py

### What is the expected behavior?
the reader.py doesn't read data on the bus

### Suggested solutions
Not sure, but I would want to confirm if there is any blocking mechanism, and what is the duration of the block?
![dds_error](https://user-images.githubusercontent.com/19335305/69162074-17571800-0aba-11ea-9ef3-ee9360526b08.png)

**Comment by samuelraeburn** [comment]
Hi Francis,

Please can you clarify what kind of error you are introducing into either the XML file or the Python script (or, even better, share a reproducer with me)?

I have run a quick test, if a syntactical error is introduced in either the Python script, or the XML file, the python process exits (with a non-zero return code).

If you are introducing a logical error in the Python script, I can believe that the process does not die (depending on what your program does). If you then correct the Python script (whilst the process is still running) your changes will not take effect since Python precompiles your script into a PYC file and runs that, this would explain why you have to restart the process, but not why you have to restart your PC.

From your "Steps to reproduce the issue" above, I think it is important to point out that when a Connector object is created, internally we parse the XML file. If there any errors in the XML file this parsing will fail.

There are various scenarios in which Connector can block (e.g., writing data), but I do not think creation is one of them. I will check this and let you know.

Please provide a code snippet or similar to help me better understand the issue.

Thanks,
Sam

**Comment by Francisobiagwu** [comment]
I believe the error comes primarily from the XML file. It happened when I tried to introduce new messages.

**Comment by samuelraeburn** [comment]
Please could you share the changes you made to the XML file + Python script?

The XML file is used to configure the system (i.e., define the DDS entities and topics), the data itself is not defined within the XML file, but is programmatically added in the Python script.

**Comment by Francisobiagwu** [comment]
XML file:

<?xml version="1.0"?>

<dds xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:noNamespaceSchemaLocation="http://community.rti.com/schema/5.1.0/rti_dds_profiles.xsd" version="5.1.0">

    
    <qos_library name="QosLibrary">
        <qos_profile name="DefaultProfile" is_default_qos="true">
            <participant_qos>
                <transport_builtin>
                    
                    <mask>SHMEM</mask>
                </transport_builtin>
            </participant_qos>

            <datareader_qos>
                
            </datareader_qos>

        </qos_profile>
    </qos_library>

    
    <types>
        <struct name="Camera" extensibility="extensible">
            <member name="id" stringMaxLength="128" id="0" type="string" key="true"/>
            <member name="value" id="1" type="long"/>
            <member name="timestamp" id="2" type="float"/>
            <member name="manufacturer" id="3" stringMaxLength="128" type="string" key="true"/>

        </struct>

        <struct name="Lidar" extensibility="extensible">
            <member name="id" stringMaxLength="128" id="0" type="string" key="true"/>
            <member name="value" id="1" type="long"/>
            <member name="timestamp" id="2" type="float"/>
            <member name="manufacturer" id="3" stringMaxLength="128" type="string" key="true"/>

        </struct>


    </types>

    
    <domain_library name="MyDomainLibrary">
        <domain name="CameraDomain" domain_id="0">
            <register_type name="Camera" kind="dynamicData" type_ref="Camera"/>
            <topic name="CameraData" register_type_ref="Camera"/>
        </domain>

        <domain name="LidarDomain" domain_id="1">
            <register_type name="Lidar" kind="dynamicData" type_ref="Lidar"/>
            <topic name="LidarData" register_type_ref="Lidar"/>
        </domain>
    </domain_library>


    
    <participant_library name="MyParticipantLibrary">


        <domain_participant name="CameraTalker" domain_ref="MyDomainLibrary::CameraDomain">
            <publisher name="CameraDataPublisher">
                <data_writer name="CameraDataWriter" topic_ref="CameraData"/>
            </publisher>

        </domain_participant>


        <domain_participant name="CameraConsole" domain_ref="MyDomainLibrary::CameraDomain">
            <subscriber name="CameraDataSubscriber">
                <data_reader name="CameraDataReader" topic_ref="CameraData"/>
            </subscriber>

        </domain_participant>






        <domain_participant name="LidarTalker" domain_ref="MyDomainLibrary::LidarDomain">
            <publisher name="LidarDataPublisher">
                <data_writer name="LidarDataWriter" topic_ref="LidarData"/>
            </publisher>

        </domain_participant>


        <domain_participant name="LidarConsole" domain_ref="MyDomainLibrary::LidarDomain">
            <subscriber name="LidarDataSubscriber">
                <data_reader name="LidarDataReader" topic_ref="LidarData"/>
            </subscriber>
        </domain_participant>


    </participant_library>
</dds>


cameraTalker.




from time import sleep
import time
print("camera dds testing")

import rticonnextdds_connector as rti



participantLibrary = 'MyParticipantLibrary::CameraTalker'  # define the domain that the participant is part of
configFile = 'Camera.xml'  # every domain participant (node) will use some form of configuration file in form of idl or xml
writer = 'CameraDataPublisher::CameraDataWriter' # define the message that the participant will write (ie publish)


connector = rti.Connector(participantLibrary, configFile) #create a connector using the defined parameters
outputDDS = connector.getOutput(writer)  # inform the connector what topic they can write



while 1:

    #this message have different parameters. ie id, value, timestamp etc
    #set those parameters
    manufacturer = 'Nikon'
    timestamp = time.time() 
    value = 25
    id = 'camera'

    outputDDS.instance.setString('id', id)
    outputDDS.instance.setNumber("value", value)
    outputDDS.instance.setNumber("timestamp", timestamp)
    outputDDS.instance.setString("manufacturer", manufacturer)



    #publish the parameters
    print('Publishing: {} {} {} {}'.format(id, value, timestamp, manufacturer))
    outputDDS.write()
    sleep(0.8)



lidartalker:

from time import sleep
import time

print("lidar dds testing")

import rticonnextdds_connector as rti

participantLibrary = 'MyParticipantLibrary::LidarTalker'  # define the domain that the participant is part of
configFile = 'Camera.xml'  # every domain participant (node) will use some form of configuration file in form of idl or xml
writer = 'LidarDataPublisher::LidarDataWriter'  # define the message that the participant will write (ie publish)

connector = rti.Connector(participantLibrary, configFile)  # create a connector using the defined parameters
outputDDS = connector.getOutput(writer)  # inform the connector what topic they can write

while 1:
    # this message have different parameters. ie id, value, timestamp etc
    # set those parameters
    manufacturer = 'Velodyne'
    timestamp = time.time()  # time.ctime()
    timestamp = time.time()
    value = 25
    id = 'Lidar'

    outputDDS.instance.setString('id', id)
    outputDDS.instance.setNumber("value", value)
    outputDDS.instance.setNumber("timestamp", timestamp)
    outputDDS.instance.setString("manufacturer", manufacturer)



    #publish the parameters
    print('Publishing: {} {} {} {}'.format(id, value, timestamp, manufacturer))
    outputDDS.write()
    sleep(1)


cameraLidarReader. I want this to listen on 2 domains and obtain two messages:

""Samples's reader."""

from __future__ import print_function
from time import sleep

import rticonnextdds_connector as rti

participantLibrary1 = 'MyParticipantLibrary::CameraConsole'
participantLibrary2 = 'MyParticipantLibrary::LidarConsole'

configFile = 'Camera.xml'


reader1 = "CameraDataSubscriber::CameraDataReader"
reader2 = "LidarDataSubscriber::LidarDataReader"

connector = rti.Connector(participantLibrary1, participantLibrary2, configFile)



inputDDS = connector.getInput(reader1, reader2)

while 1:
    inputDDS.take() # i think this means obtain message on the DDS bus.
    numOfSamples = inputDDS.samples.getLength()
    #print('number of samples: ', numOfSamples)
    try:
        for j in range(0, numOfSamples):
            if inputDDS.infos.isValid(j):
                # This gives you a dictionary
                sample = inputDDS.samples.getDictionary(j)
                print('sample: ', sample)

    except:
        print('Error occurred')

    sleep(2)

**Comment by Francisobiagwu** [comment]
Here is another error I noticed:
The Lidar reader is not updating the timestamp. It keeps printing the same timestamp over and over again. 

![error_in_dds](https://user-images.githubusercontent.com/19335305/69566045-322b0000-0f84-11ea-88e4-d29049931778.png)

**Comment by samuelraeburn** [comment]
Hi,

I've been looking into your code and have noticed a few things that I think you should address:

- In lidarReader.py you are not correctly creating the Connector.
  - `connector = rti.Connector(participantLibrary1, participantLibrary2, configFile)` is invalid. Each `Connector` object is defined by a single `Domain Participant` in the configuration XML file. For this reason you cannot create a `Connector` object with two `Domain Participants`. You will need to create two `Connector` objects (one for participantLibrary1 and the other for participantLibrary2). 
- In lidarReader.py you are not correctly creating the Input.
  - `inputDDS = connector.getInput(reader1, reader2)` is incorrect. In Connector, there is a one-to-one mapping between a `DDS DataReader` and an `Input`, so it doesn't make sense to create an input with two DataReaders. You should create a separate Input for each `DataReader`.
- There is an error in your XML file, the tag `<participant_library>`, should be `<domain_participant_library>`.

The reason that your timestamp is not changing is that it is being truncated. One option would be to store it as a string instead. This would involve modifying your XML definition of the member to be `<member name="timestamp" id="2" type="string", stringMaxLength="128"/>` and then setting it within your code as `timestamp = str(time.time())`. Is this an option for you?

**Comment by samuelraeburn** [comment]
One other thing, there is no need to specify `kind="dynamicData"` in the XML configuration file. Every Connector application uses Dynamic Data internally.

**Comment by Francisobiagwu** [comment]
Thanks. That resolved the issue.
