### ISSUE TITLE
how to subscribe to multiple messages on different domain

### ISSUE THREAD

**Issue by Francisobiagwu** [rticommunity/rticonnextdds-connector-py#37]
From the python example template, I created a new domain and then I attempted to have a participant subscribe to data from two different domains. But it seemed like I cannot use the same domain_participant name twice. Please, do I change this xml to make this possible?

    
    <domain_library name="MyDomainLibrary">
        <domain name="CameraDomain" domain_id="0">
            <register_type name="Camera" kind="dynamicData" type_ref="Camera"/>
            <topic name="CameraData" register_type_ref="Camera"/>
        </domain>

        <domain name="LidarDomain" domain_id="1">
            <register_type name="Lidar" kind="dynamicData" type_ref="Lidar"/>
            <topic name="LidarData" register_type_ref="Lidar"/>
        </domain>
    </domain_library>

    <participant_library name="MyParticipantLibrary">

        <domain_participant name="Console" domain_ref="MyDomainLibrary::CameraDomain">
            <subscriber name="CameraDataSubscriber">
                <data_reader name="CameraDataReader" topic_ref="CameraData"/>
            </subscriber>

        </domain_participant>

        <domain_participant name="Console" domain_ref="MyDomainLibrary::LidarDomain">
            <subscriber name="LidarDataSubscriber">
                <data_reader name="LidarDataReader" topic_ref="LidarData"/>
            </subscriber>
        </domain_participant>

    </participant_library>

**Comment by samuelraeburn** [comment]
Internally, Connector relies on [RTI's XML Application Creation](https://community.rti.com/static/documentation/connext-dds/current/doc/manuals/connext_dds/xml_application_creation/html_files/RTI_ConnextDDS_CoreLibraries_XML_AppCreation_GettingStarted/index.htm#XMLBasedAppCreation/UnderstandingPrototyper/XMLTagsConfigEntities.htm%3FTocPath%3D5.%2520Understanding%2520XML-Based%2520Application%2520Creation%7C5.5%2520XML%2520Tags%2520for%2520Configuring%2520Entities%7C_____0) for its configuration. The way a Participant is identified in Connector is of the form `MyParticipantLibrary::MyParticipant`, so even though in your attached XML the Participants have different `domain_ref` tags, this is orthogonal to the definition of the Participant. Internally we have no way of knowing which Participant you are referring to when you create the Connector.

I think your best option is to rename the DomainParticipants, e.g.:
```
<participant_library name="MyParticipantLibrary">
    <domain_participant name="CameraConsole" domain_ref="MyDomainLibrary::CameraDomain">
        <subscriber name="CameraDataSubscriber">
            <data_reader name="CameraDataReader" topic_ref="CameraData"/>
        </subscriber>
    </domain_participant>
    <domain_participant name="LidarConsole" domain_ref="MyDomainLibrary::LidarDomain">
        <subscriber name="LidarDataSubscriber">
            <data_reader name="LidarDataReader" topic_ref="LidarData"/>
        </subscriber>
    </domain_participant>
</participant_library>
```

If this isn't an option for you, you will need to create two XML files, one defining the entities for the Lidar and the other containing entities for the Camera. Doing this, the two Participants can have the same name.

Let me know if that helps,
Sam

**Comment by Francisobiagwu** [comment]
Here is my code:
###############################################################################
# (c) 2005-2015 Copyright, Real-Time Innovations.  All rights reserved.       #
# No duplications, whole or partial, manual or electronic, may be made        #
# without express written permission.  Any such copies, or revisions thereof, #
# must display this notice unaltered.                                         #
# This code contains trade secrets of Real-Time Innovations, Inc.             #
###############################################################################

"""Samples's reader."""

from __future__ import print_function
from time import sleep

import rticonnextdds_connector as rti

participantLibrary1 = 'MyParticipantLibrary::CameraConsole'
participantLibrary2 = 'MyParticipantLibrary::LidarConsole'

configFile = 'Camera.xml'


reader1 = "CameraDataSubscriber::CameraDataReader"
reader2 = "LidarDataSubscriber::LidarDataReader"

connector = rti.Connector(participantLibrary1, participantLibrary2, configFile)



inputDDS = connector.getInput(reader1, reader2)

while 1:
    inputDDS.take() # i think this means obtain message on the DDS bus.
    numOfSamples = inputDDS.samples.getLength()
    #print('number of samples: ', numOfSamples)
    try:
        for j in range(0, numOfSamples):
            if inputDDS.infos.isValid(j):
                # This gives you a dictionary
                sample = inputDDS.samples.getDictionary(j)
                print('sample: ', sample)

    except:
        print('Error occurred')

    sleep(2)




here is the XML:
<?xml version="1.0"?>

<dds xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:noNamespaceSchemaLocation="http://community.rti.com/schema/5.1.0/rti_dds_profiles.xsd" version="5.1.0">

    
    <qos_library name="QosLibrary">
        <qos_profile name="DefaultProfile" is_default_qos="true">
            <participant_qos>
                <transport_builtin>
                    
                    <mask>SHMEM</mask>
                </transport_builtin>
            </participant_qos>

            <datareader_qos>
                
            </datareader_qos>

        </qos_profile>
    </qos_library>

    
    <types>
        <struct name="Camera" extensibility="extensible">
            <member name="id" stringMaxLength="128" id="0" type="string" key="true"/>
            <member name="value" id="1" type="long"/>
            <member name="timestamp" id="2" type="float"/>
            <member name="manufacturer" id="3" stringMaxLength="128" type="string" key="true"/>

        </struct>

        <struct name="Lidar" extensibility="extensible">
            <member name="id" stringMaxLength="128" id="0" type="string" key="true"/>
            <member name="value" id="1" type="long"/>
            <member name="timestamp" id="2" type="float"/>
            <member name="manufacturer" id="3" stringMaxLength="128" type="string" key="true"/>

        </struct>


    </types>

    
    <domain_library name="MyDomainLibrary">
        <domain name="CameraDomain" domain_id="0">
            <register_type name="Camera" kind="dynamicData" type_ref="Camera"/>
            <topic name="CameraData" register_type_ref="Camera"/>
        </domain>

        <domain name="LidarDomain" domain_id="1">
            <register_type name="Lidar" kind="dynamicData" type_ref="Lidar"/>
            <topic name="LidarData" register_type_ref="Lidar"/>
        </domain>
    </domain_library>


    
    <participant_library name="MyParticipantLibrary">


        <domain_participant name="CameraTalker" domain_ref="MyDomainLibrary::CameraDomain">
            <publisher name="CameraDataPublisher">
                <data_writer name="CameraDataWriter" topic_ref="CameraData"/>
            </publisher>

        </domain_participant>


        <domain_participant name="CameraConsole" domain_ref="MyDomainLibrary::CameraDomain">
            <subscriber name="CameraDataSubscriber">
                <data_reader name="CameraDataReader" topic_ref="CameraData"/>
            </subscriber>

        </domain_participant>






        <domain_participant name="LidarTalker" domain_ref="MyDomainLibrary::LidarDomain">
            <publisher name="LidarDataPublisher">
                <data_writer name="LidarDataWriter" topic_ref="LidarData"/>
            </publisher>

        </domain_participant>


        <domain_participant name="LidarConsole" domain_ref="MyDomainLibrary::LidarDomain">
            <subscriber name="LidarDataSubscriber">
                <data_reader name="LidarDataReader" topic_ref="LidarData"/>
            </subscriber>
        </domain_participant>


    </participant_library>
</dds>

**Comment by samuelraeburn** [comment]
Great. Is that working for you now then?

**Comment by samuelraeburn** [comment]
See my comments on the other issue you opened (#36 ) about why this isn't working.
