### ISSUE TITLE
Auto-filled sequences 

### ISSUE THREAD

**Issue by SMONTA** [rticommunity/rticonnextdds-connector-py#39]
I am trying to test the routing service by using this connector to publish data then read them and check if the output is the same as the input or not. But I got a weird behavior. I receive extra data in sequence (sample2 has information of sample1). I tried version 5.3.0 and version 6.0.1 and all give the same behavior. 
My type:
       ` <typedef name="key_t" stringMaxLength="31" type="string"/>
          <typedef name="value_t" stringMaxLength="31" type="string"/>
  <struct name="Health_Topic">
            <member name="key" type="nonBasic" nonBasicTypeName="key_t" key="true"/>
            <member name="value" sequenceMaxLength="32" type="nonBasic" nonBasicTypeName="value_t"/>
        </struct> 
`
data input: 
`[
  {
    "key": "key_1",
    "value": [
      "Server_1",
      "Server_2",
      "Server_3",
      "Server_4"
    ]
  },
  {
    "key": "key_2",
    "value": [
      "Server_1",
      "Server_4"
    ]
  },
  {
    "key": "key_3",
    "value": [
      "Server_6",
      "Server_7",
      "Server_2",
      "Server_5"
    ]
  }
]`
received data:
`[
  {
    "key": "key_1",
    "value": [
      "Server_1",
      "Server_2",
      "Server_3",
      "Server_4"
    ]
  },
  {
    "key": "key_2",
    "value": [
      "Server_1",
      "Server_4",
      "Server_3",
      "Server_4"
    ]
  },
  {
    "key": "key_3",
    "value": [
      "Server_6",
      "Server_7",
      "Server_2",
      "Server_5"
    ]
  }
]`
For Qos I used BestEffort.
Any idea why/how to fix it?

**Comment by gianpiero** [comment]
Hello @SMONTA 

did you try to call ```clear_member``` right after the write? That should fix the issue. 

Best,
  Gianpiero

**Comment by SMONTA** [comment]
Hello Gianpiero, 
it works fine. 
Best,
