### ISSUE TITLE
Communication Within a Single LAN

### ISSUE THREAD

**Issue by cyxiaotian** [rticommunity/rticonnextdds-connector-py#52]
so, i want to modify the simple demo of **rticonnextdds-connector-py** that i can communicate with two separate applications(each one running in a windows pc). But i failure!  should i modify the xml? or can you give me some advise aboult it.. thanks~

**Comment by samuelraeburn** [comment]
Hey, that should just work out of the box, maybe it is a firewall issue on one of the machines?
This article outlines some possible sources of error: https://community.rti.com/kb/why-are-my-reader-and-writer-applications-unable-communicate
