### ISSUE TITLE
Support on Jetson nano

### ISSUE THREAD

**Issue by ztz1989** [rticommunity/rticonnextdds-connector-py#73]
Dear experts,

Do you know if this python connector is supported on Nvidia Jetson nano (aarch64)? 

I have tried the simple read/writer example, but the shared .so file cannot be loaded: 

`/home/rticonnextdds-connector-py/rticonnextdds_connector/../rticonnextdds-connector/lib/x64Linux2.6gcc4.4.5/librtiddsconnector.so: cannot open shared object file: No such file or directory`

I have tried the same on a Raspberry PI 4 and everything worked perfectly. So do you guys know how to make it work also on Jetson nano? Any info or hint will be highly appreciated. 

Thanks & Regards,
Tianzhu

**Comment by samuelraeburn** [comment]
Hi Tianzhu,

Support for ARMv8 (aarch64) will be added in our next Connector release, currently scheduled for Q2 2021.

Sam

**Comment by ztz1989** [comment]
Thanks a lot for the info, Sam. I'll wait for it. 

Best regards,
Tianzhu
